{
 "title": "4 Golden Signals sX CNP",
 "tags": [ "4GoldenSignals" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values({namespace=\"$namespace\"}, workload) "
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values({exported_namespace=\"$namespace\"}, exported_service) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage Total per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=~\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"\", namespace=~\"$namespace\", workload=~\"$workload\", workload_type=\"deployment\"}\n) by (workload,pod)\n"
    }
   ]
  },
  {
   "title": "Memory usage Total per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"\", namespace=~\"$namespace\", workload_type=\"deployment\", workload=~\"$workload\"}\n) by (workload,pod)"
    }
   ]
  },
  {
   "title": "Network Receive bandwidth per pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=~\"$namespace\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"\", namespace=~\"$namespace\", workload_type=\"deployment\",workload=~\"$workload\"}) by (workload,pod)"
    }
   ]
  },
  {
   "title": "Network Transmit bandwidth per pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=~\"$namespace\"}[5m])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"\", namespace=~\"$namespace\", workload_type=\"deployment\",workload=~\"$workload\"}) by (workload,pod)"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Traffic - Anzahl Requests pro Sekunde",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_service,code) (rate(haproxy_server_http_responses_total{exported_service=~\"$service\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Traffic per Pod",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_service,code,exported_pod) (rate(haproxy_server_http_responses_total{exported_service=~\"$service\"}[$__interval]))"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Latency per Router-Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_service, pod)(haproxy_server_http_average_response_latency_milliseconds{exported_namespace=~\"$namespace\",exported_service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Latency per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by(exported_service,exported_pod,pod)(haproxy_server_http_average_response_latency_milliseconds{exported_namespace=~\"$namespace\",exported_service=~\"$service\"})"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Error Rate [%]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (exported_service) (rate(haproxy_server_http_responses_total{exported_service=~\"$service\",code!=\"2xx\"}[$__interval])) / sum  by (exported_service) (rate(haproxy_server_http_responses_total{exported_service=~\"$service\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Error rate per Pod [%]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (exported_service,exported_pod) (rate(haproxy_server_http_responses_total{exported_service=~\"$service\",code!=\"2xx\"}[$__interval])) / sum  by (exported_service,exported_pod) (rate(haproxy_server_http_responses_total{exported_service=~\"$service\"}[$__interval])))"
    }
   ]
  }
 ]
}